server:
  port: 8888
spring:
  application:
    name: openfeign
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

logging:
  level:
    com:
      xc:
        openfeign8888:
          service: debug