server:
  port: 8083
spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

# 微服务提供者的名称
service-url:
  nacos-user-service: http://nacos-config-client