server:
  port: 9999
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true  # 开启通过服务名自动注册路由
      routes: # 路由
        - id: nacos-provider
          uri: lb://nacos-provider
          predicates:
            - Path=/xc/**
            - After=2023-08-26T14:26:42.052+08:00[Asia/Shanghai]